name: calendar
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kalender: ^0.11.1
  syncfusion_flutter_calendar: ^30.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
